#!/usr/bin/perl

# File generated by menutray v0.54

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit ~/.config/menutray/schema.pl instead!

use utf8;
use strict;
use Gtk3 ('-init');

my $menu = 'Gtk3::Menu'->new;
my $icon = 'Gtk3::StatusIcon'->new;

my $menutray_title   = "menutray";
my $menutray_tooltip = "Applications";

if (defined($menutray_title) and 0) {
    $icon->set_title($menutray_title);
    $icon->set_name('');
}

if (defined($menutray_tooltip) and 0) {
    $icon->set_tooltip($menutray_tooltip);
}

$icon->set_from_icon_name('start-here');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

local $SIG{USR1} = \&show_icon_menu;

load_menu();

sub show_icon_menu {
    my (undef, $event) = @_;

    if (ref($event) and $event->button == 3) {

        my $right_click = 'Gtk3::Menu'->new;
        {
            my $regenerate = 'Gtk3::ImageMenuItem'->new("_Regenerate");
            $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
            $regenerate->set_image('Gtk3::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
            $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk3'->main_quit});
            $right_click->append($regenerate);
        }

        {
            my $quit = 'Gtk3::ImageMenuItem'->new("_Quit");
            $quit->set_property('tooltip_text', "Close\ this\ application\.");
            $quit->set_image('Gtk3::Image'->new_from_icon_name("application\-exit",q{menu}));
            $quit->signal_connect('activate', sub { 'Gtk3'->main_quit });
            $right_click->append($quit);
        }

        $right_click->show_all;
        $right_click->popup(undef, undef, sub {
            my ($x, $y, @list) = Gtk3::StatusIcon::position_menu($right_click, 0, 0, $icon);
            if (0) {
                ($x, $y) = @_[1,2];
                if (0) {
                    $right_click->set_monitor(Gtk2::Gdk::Screen->get_default->get_monitor_at_point($x, $y));
                } else {
                    $right_click->set_monitor(Gtk3::Gdk::Screen::get_default()->get_monitor_at_point($x, $y));
                }
            }
            ($x, $y, @list);
        }, [1, 1], 0, 0);

        return 1;
    }
    $menu->popup(undef, undef, sub {
            my ($x, $y, @list) = Gtk3::StatusIcon::position_menu($menu, 0, 0, $icon);
            if (0) {
                ($x, $y) = @_[1,2];
                if (0) {
                    $menu->set_monitor(Gtk2::Gdk::Screen->get_default->get_monitor_at_point($x, $y));
                } else {
                    $menu->set_monitor(Gtk3::Gdk::Screen::get_default()->get_monitor_at_point($x, $y));
                }
            }
            ($x, $y, @list);
        }, [1, 1], 0, 0);

    return 1;
}

sub load_menu {
{
    my $item = 'Gtk3::ImageMenuItem'->new("_File\ Manager");
    $item->set_image('Gtk3::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ \. &"});
    $menu->append($item);
}

{
    my $item = 'Gtk3::ImageMenuItem'->new("_Terminal");
    $item->set_image('Gtk3::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $item->signal_connect('activate', sub {system "xterm &"});
    $menu->append($item);
}

{
    my $item = 'Gtk3::ImageMenuItem'->new("_Web\ Browser");
    $item->set_image('Gtk3::Image'->new_from_icon_name("web\-browser",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ http\:\/\/ &"});
    $menu->append($item);
}

{
    my $item = 'Gtk3::ImageMenuItem'->new("_Run\ command");
    $item->set_image('Gtk3::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "gmrun &"});
    $menu->append($item);
}


    $menu->append('Gtk3::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Accessories");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Ark");
    $app->signal_connect('activate', sub {system "ark &"});
    $app->set_property('tooltip_text', "Work\ with\ file\ archives");
    $app->set_image('Gtk3::Image'->new_from_icon_name("ark",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Clock");
    $app->signal_connect('activate', sub {system "kclock &"});
    $app->set_property('tooltip_text', "Set\ alarms\ and\ timers\,\ use\ a\ stopwatch\,\ and\ manage\ world\ clocks");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.kde\.kclock",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_CurseForge");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/curseforge &"});
    $app->set_property('tooltip_text', "The\ CurseForge\ Electron\ App");
    $app->set_image('Gtk3::Image'->new_from_icon_name("curseforge",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Emoji\ Selector");
    $app->signal_connect('activate', sub {system "plasma\-emojier &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-desktop\-emoticons",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Kate");
    $app->signal_connect('activate', sub {system "kate\ \-b &"});
    $app->set_property('tooltip_text', "KDE\ Advanced\ Text\ Editor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kate",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KeePassXC");
    $app->signal_connect('activate', sub {system "keepassxc &"});
    $app->set_property('tooltip_text', "Community\-driven\ port\ of\ the\ Windows\ application\ \“KeePass\ Password\ Safe\”");
    $app->set_image('Gtk3::Image'->new_from_icon_name("keepassxc",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ksnip");
    $app->signal_connect('activate', sub {system "ksnip &"});
    $app->set_property('tooltip_text', "Cross\-platform\ screenshot\ tool\ that\ provides\ many\ annotation\ features\ for\ your\ screenshots\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("ksnip",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KWrite");
    $app->signal_connect('activate', sub {system "kwrite &"});
    $app->set_property('tooltip_text', "KDE\ Text\ Editor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kwrite",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_OpenRGB");
    $app->signal_connect('activate', sub {system "openrgb &"});
    $app->set_property('tooltip_text', "Control\ RGB\ lighting");
    $app->set_image('Gtk3::Image'->new_from_icon_name("OpenRGB",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Solaar");
    $app->signal_connect('activate', sub {system "solaar &"});
    $app->set_property('tooltip_text', "Logitech\ Unifying\ Receiver\ peripherals\ manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("solaar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Vim");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'vim\' &"});
    $app->set_property('tooltip_text', "Edit\ text\ files");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gvim",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Weather");
    $app->signal_connect('activate', sub {system "kweather &"});
    $app->set_property('tooltip_text', "View\ real\-time\ weather\ forecasts\ and\ other\ information");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.kde\.kweather",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Welcome\ Center");
    $app->signal_connect('activate', sub {system "plasma\-welcome &"});
    $app->set_property('tooltip_text', "Friendly\ onboarding\ wizard\ for\ Plasma");
    $app->set_image('Gtk3::Image'->new_from_icon_name("start\-here\-kde\-plasma",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Winetricks");
    $app->signal_connect('activate', sub {system "winetricks\ \-\-gui &"});
    $app->set_property('tooltip_text', "Work\ around\ problems\ and\ install\ applications\ under\ Wine");
    $app->set_image('Gtk3::Image'->new_from_icon_name("winetricks",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Development");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Antares");
    $app->signal_connect('activate', sub {system "antares\-sql &"});
    $app->set_property('tooltip_text', "A\ modern\,\ fast\ and\ productivity\ driven\ SQL\ client\ with\ a\ focus\ in\ UX\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("antares\-sql",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Code\ \-\ OSS");
    $app->signal_connect('activate', sub {system "code\-oss\ \-\-unity\-launch &"});
    $app->set_property('tooltip_text', "Code\ Editing\.\ Redefined\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("com\.visualstudio\.code\.oss",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Electron\ 27");
    $app->signal_connect('activate', sub {system "electron27 &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("electron27",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Electron\ 28");
    $app->signal_connect('activate', sub {system "electron28 &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("electron28",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_FLUID");
    $app->signal_connect('activate', sub {system "fluid &"});
    $app->set_property('tooltip_text', "FLTK\ GUI\ Designer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("fluid",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_JetBrains\ Toolbox");
    $app->signal_connect('activate', sub {system "\/home\/chads\/\.local\/share\/JetBrains\/Toolbox\/bin\/jetbrains\-toolbox &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/JetBrains\/Toolbox\/toolbox\.svg",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Kate");
    $app->signal_connect('activate', sub {system "kate\ \-b &"});
    $app->set_property('tooltip_text', "KDE\ Advanced\ Text\ Editor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kate",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KDevelop");
    $app->signal_connect('activate', sub {system "kdevelop &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("kdevelop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KDevelop\ \(Pick\ Session\)");
    $app->signal_connect('activate', sub {system "kdevelop\ \-\-ps &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("kdevelop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_PhpStorm\ 2023\.3\.6");
    $app->signal_connect('activate', sub {system "\"\/home\/chads\/\.local\/share\/JetBrains\/Toolbox\/apps\/phpstorm\/bin\/phpstorm\.sh\" &"});
    $app->set_property('tooltip_text', "A\ smart\ IDE\ for\ PHP\ and\ Web");
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/JetBrains\/Toolbox\/apps\/phpstorm\/bin\/phpstorm\.svg",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ Assistant");
    $app->signal_connect('activate', sub {system "assistant &"});
    $app->set_property('tooltip_text', "Shows\ Qt\ documentation\ and\ examples");
    $app->set_image('Gtk3::Image'->new_from_icon_name("assistant",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ Designer");
    $app->signal_connect('activate', sub {system "designer &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt\ applications");
    $app->set_image('Gtk3::Image'->new_from_icon_name("QtProject\-designer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ Linguist");
    $app->signal_connect('activate', sub {system "linguist &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt\ applications");
    $app->set_image('Gtk3::Image'->new_from_icon_name("linguist",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ QDBusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk3::Image'->new_from_icon_name("qdbusviewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_UserFeedback\ Console");
    $app->signal_connect('activate', sub {system "UserFeedbackConsole &"});
    $app->set_property('tooltip_text', "Analytics\ and\ administration\ tool\ for\ UserFeedback\ servers\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("search",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # EDUCATION # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Education");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-science",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # GAMES # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Games");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-games",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Baldur\'s\ Gate\ 3");
    $app->signal_connect('activate', sub {system "steam\ steam\:\/\/rungameid\/1086940 &"});
    $app->set_property('tooltip_text', "Play\ this\ game\ on\ Steam");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam_icon_1086940",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Blizzard\ Battle\.net");
    $app->signal_connect('activate', sub {system "env\ LUTRIS_SKIP_INIT\=1\ lutris\ lutris\:rungameid\/1 &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("lutris_battlenet",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_HELLDIVERS™\ 2");
    $app->signal_connect('activate', sub {system "steam\ steam\:\/\/rungameid\/553850 &"});
    $app->set_property('tooltip_text', "Play\ this\ game\ on\ Steam");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam_icon_553850",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Lutris");
    $app->signal_connect('activate', sub {system "lutris &"});
    $app->set_property('tooltip_text', "Video\ Game\ Preservation\ Platform");
    $app->set_image('Gtk3::Image'->new_from_icon_name("lutris",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Proton\ Experimental");
    $app->signal_connect('activate', sub {system "steam\ steam\:\/\/rungameid\/1493710 &"});
    $app->set_property('tooltip_text', "Play\ this\ game\ on\ Steam");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Steam\ \(Runtime\)");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/steam\-runtime &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ and\ playing\ games\ on\ Steam");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Steam\ Linux\ Runtime\ 3\.0\ \(sniper\)");
    $app->signal_connect('activate', sub {system "steam\ steam\:\/\/rungameid\/1628350 &"});
    $app->set_property('tooltip_text', "Play\ this\ game\ on\ Steam");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Strongbox");
    $app->signal_connect('activate', sub {system "strongbox &"});
    $app->set_property('tooltip_text', "World\ of\ Warcraft\ addon\ manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("strongbox",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Graphics");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_GNU\ Image\ Manipulation\ Program");
    $app->signal_connect('activate', sub {system "gimp\-2\.10 &"});
    $app->set_property('tooltip_text', "Create\ images\ and\ edit\ photographs");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gimp",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Gwenview");
    $app->signal_connect('activate', sub {system "gwenview &"});
    $app->set_property('tooltip_text', "A\ simple\ image\ viewer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gwenview",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KColorChooser");
    $app->signal_connect('activate', sub {system "kcolorchooser &"});
    $app->set_property('tooltip_text', "Color\ selector\ and\ palette\ editor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kcolorchooser",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Okular");
    $app->signal_connect('activate', sub {system "okular &"});
    $app->set_property('tooltip_text', "Universal\ document\ viewer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("okular",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Multimedia");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_HandBrake");
    $app->signal_connect('activate', sub {system "ghb &"});
    $app->set_property('tooltip_text', "Transcodes\ DVD\,\ Blu\-ray\,\ and\ other\ media");
    $app->set_image('Gtk3::Image'->new_from_icon_name("fr\.handbrake\.ghb",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Kdenlive");
    $app->signal_connect('activate', sub {system "kdenlive &"});
    $app->set_property('tooltip_text', "Nonlinear\ video\ editor\ by\ KDE");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kdenlive",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_mpv\ Media\ Player");
    $app->signal_connect('activate', sub {system "mpv\ \-\-player\-operation\-mode\=pseudo\-gui\ \-\- &"});
    $app->set_property('tooltip_text', "Play\ movies\ and\ songs");
    $app->set_image('Gtk3::Image'->new_from_icon_name("mpv",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_OBS\ Studio");
    $app->signal_connect('activate', sub {system "obs &"});
    $app->set_property('tooltip_text', "Free\ and\ Open\ Source\ Streaming\/Recording\ Software");
    $app->set_image('Gtk3::Image'->new_from_icon_name("com\.obsproject\.Studio",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_PlasmaTube");
    $app->signal_connect('activate', sub {system "plasmatube &"});
    $app->set_property('tooltip_text', "Watch\ \(YouTube\)\ videos");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.kde\.plasmatube",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ V4L2\ test\ Utility");
    $app->signal_connect('activate', sub {system "qv4l2 &"});
    $app->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app->set_image('Gtk3::Image'->new_from_icon_name("qv4l2",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ V4L2\ video\ capture\ utility");
    $app->signal_connect('activate', sub {system "qvidcap &"});
    $app->set_property('tooltip_text', "Viewer\ for\ video\ capture");
    $app->set_image('Gtk3::Image'->new_from_icon_name("qvidcap",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Spotify\ \(Launcher\)");
    $app->signal_connect('activate', sub {system "spotify\-launcher &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("spotify\-launcher",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Tubi");
    $app->signal_connect('activate', sub {system "tubi &"});
    $app->set_property('tooltip_text', "Unofficial\ Tubi\ desktop\ application");
    $app->set_image('Gtk3::Image'->new_from_icon_name("tubi",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_VLC\ media\ player");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vlc\ \-\-started\-from\-file &"});
    $app->set_property('tooltip_text', "Read\,\ capture\,\ broadcast\ your\ multimedia\ streams");
    $app->set_image('Gtk3::Image'->new_from_icon_name("vlc",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Volume\ Icon");
    $app->signal_connect('activate', sub {system "volumeicon &"});
    $app->set_property('tooltip_text', "Lightweight\ volume\ control\ for\ the\ systray");
    $app->set_image('Gtk3::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Network");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Avahi\ SSH\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ SSH\ Servers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Avahi\ VNC\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ VNC\ Servers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Discord");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/discord &"});
    $app->set_property('tooltip_text', "All\-in\-one\ voice\ and\ text\ chat\ for\ gamers\ that\'s\ free\,\ secure\,\ and\ works\ on\ both\ your\ desktop\ and\ phone\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("discord",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Firefox\ Web\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/firefox\/firefox &"});
    $app->set_property('tooltip_text', "Browse\ the\ World\ Wide\ Web");
    $app->set_image('Gtk3::Image'->new_from_icon_name("firefox",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KDE\ Connect");
    $app->signal_connect('activate', sub {system "kdeconnect\-app &"});
    $app->set_property('tooltip_text', "Make\ all\ your\ devices\ one");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kdeconnect",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KDE\ Connect\ Indicator");
    $app->signal_connect('activate', sub {system "kdeconnect\-indicator &"});
    $app->set_property('tooltip_text', "Display\ information\ about\ your\ devices");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kdeconnect",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KDE\ Connect\ SMS");
    $app->signal_connect('activate', sub {system "kdeconnect\-sms &"});
    $app->set_property('tooltip_text', "Text\ Messaging");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kdeconnect",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KTorrent");
    $app->signal_connect('activate', sub {system "ktorrent &"});
    $app->set_property('tooltip_text', "A\ BitTorrent\ program\ by\ KDE");
    $app->set_image('Gtk3::Image'->new_from_icon_name("ktorrent",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Microsoft\ Teams\ for\ Linux");
    $app->signal_connect('activate', sub {system "teams\-for\-linux &"});
    $app->set_property('tooltip_text', "Unofficial\ Microsoft\ Teams\ client\ for\ Linux\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("teams\-for\-linux",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_NeoChat");
    $app->signal_connect('activate', sub {system "neochat &"});
    $app->set_property('tooltip_text', "Client\ for\ the\ Matrix\ protocol");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.kde\.neochat",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Remote\ Viewer");
    $app->signal_connect('activate', sub {system "remote\-viewer &"});
    $app->set_property('tooltip_text', "Access\ remote\ desktops");
    $app->set_image('Gtk3::Image'->new_from_icon_name("virt\-viewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Steam\ \(Runtime\)");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/steam\-runtime &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ and\ playing\ games\ on\ Steam");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Thunderbird");
    $app->signal_connect('activate', sub {system "thunderbird &"});
    $app->set_property('tooltip_text', "Send\ and\ receive\ mail\ with\ Thunderbird");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.mozilla\.Thunderbird",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_TigerVNC\ Viewer");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vncviewer &"});
    $app->set_property('tooltip_text', "Connect\ to\ VNC\ server\ and\ display\ remote\ desktop");
    $app->set_image('Gtk3::Image'->new_from_icon_name("tigervnc",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Vivaldi");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vivaldi\-stable &"});
    $app->set_property('tooltip_text', "Access\ the\ Internet");
    $app->set_image('Gtk3::Image'->new_from_icon_name("vivaldi",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # OFFICE # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Office");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice");
    $app->signal_connect('activate', sub {system "libreoffice &"});
    $app->set_property('tooltip_text', "Launch\ applications\ to\ create\ text\ documents\,\ spreadsheets\,\ presentations\,\ drawings\,\ formulas\,\ and\ databases\,\ or\ open\ recently\ used\ documents\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-startcenter",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Base");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-base &"});
    $app->set_property('tooltip_text', "Manage\ databases\,\ create\ queries\ and\ reports\ to\ track\ and\ manage\ your\ information\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-base",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Calc");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-calc &"});
    $app->set_property('tooltip_text', "Perform\ calculations\,\ analyze\ information\ and\ manage\ lists\ in\ spreadsheets\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-calc",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Impress");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-impress &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ presentations\ for\ slideshows\,\ meetings\ and\ Web\ pages\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-impress",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Writer");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-writer &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ text\ and\ graphics\ in\ letters\,\ reports\,\ documents\ and\ Web\ pages\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-writer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Obsidian");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/obsidian &"});
    $app->set_property('tooltip_text', "Obsidian");
    $app->set_image('Gtk3::Image'->new_from_icon_name("obsidian",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Okular");
    $app->signal_connect('activate', sub {system "okular &"});
    $app->set_property('tooltip_text', "Universal\ document\ viewer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("okular",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # OTHER # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Other");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-other",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Android\ Keyboard\ \(AOSP\)");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.inputmethod\.latin &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.inputmethod\.latin\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Browser");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ org\.lineageos\.jelly &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/org\.lineageos\.jelly\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Calculator");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.calculator2 &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.calculator2\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Calendar");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ org\.lineageos\.etar &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/org\.lineageos\.etar\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Camera");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.camera2 &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.camera2\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Chrome");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.chrome &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.chrome\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Clock");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.deskclock &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.deskclock\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Contacts");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.contacts &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.contacts\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Files");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.documentsui &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.documentsui\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Gallery");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.gallery3d &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.gallery3d\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Google\ Play\ Store");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.vending &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.vending\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Help");
    $app->signal_connect('activate', sub {system "khelpcenter &"});
    $app->set_property('tooltip_text', "Browse\ and\ search\ documentation");
    $app->set_image('Gtk3::Image'->new_from_icon_name("help\-browser",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Music");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ org\.lineageos\.eleven &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/org\.lineageos\.eleven\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Recorder");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ org\.lineageos\.recorder &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/org\.lineageos\.recorder\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Rofi");
    $app->signal_connect('activate', sub {system "rofi\ \-show &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("rofi",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Rofi\ Theme\ Selector");
    $app->signal_connect('activate', sub {system "rofi\-theme\-selector &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("rofi",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Settings");
    $app->signal_connect('activate', sub {system "waydroid\ app\ launch\ com\.android\.settings &"});
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/home\/chads\/\.local\/share\/waydroid\/data\/icons\/com\.android\.settings\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Waydroid");
    $app->signal_connect('activate', sub {system "waydroid\ show\-full\-ui &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("waydroid",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Settings");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Advanced\ Network\ Configuration");
    $app->signal_connect('activate', sub {system "nm\-connection\-editor &"});
    $app->set_property('tooltip_text', "Manage\ and\ change\ your\ network\ connection\ settings");
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-system\-network",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ARandR");
    $app->signal_connect('activate', sub {system "arandr &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("display",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KDE\ Connect\ Settings");
    $app->signal_connect('activate', sub {system "kdeconnect\-settings &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("kdeconnect",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KDE\ System\ Settings");
    $app->signal_connect('activate', sub {system "systemsettings &"});
    $app->set_property('tooltip_text', "Configuration\ tools\ for\ your\ computer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-system",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_NVIDIA\ X\ Server\ Settings");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/nvidia\-settings &"});
    $app->set_property('tooltip_text', "Configure\ NVIDIA\ X\ Server\ Settings");
    $app->set_image('Gtk3::Image'->new_from_icon_name("nvidia\-settings",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Print\ Settings");
    $app->signal_connect('activate', sub {system "system\-config\-printer &"});
    $app->set_property('tooltip_text', "Configure\ printers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("printer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_System\ Settings");
    $app->signal_connect('activate', sub {system "systemsettings &"});
    $app->set_property('tooltip_text', "Configuration\ tools\ for\ your\ computer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-system",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_System");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Avahi\ Zeroconf\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\ services\ available\ on\ your\ network");
    $app->set_image('Gtk3::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_btop\+\+");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'btop\' &"});
    $app->set_property('tooltip_text', "Resource\ monitor\ that\ shows\ usage\ and\ stats\ for\ processor\,\ memory\,\ disks\,\ network\ and\ processes");
    $app->set_image('Gtk3::Image'->new_from_icon_name("btop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_conky");
    $app->signal_connect('activate', sub {system "conky\ \-\-daemonize\ \-\-pause\=1 &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("conky\-logomark\-violet",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Crashed\ Processes\ Viewer");
    $app->signal_connect('activate', sub {system "drkonqi\-coredump\-gui &"});
    $app->set_property('tooltip_text', "Offers\ detailed\ view\ of\ past\ crashes");
    $app->set_image('Gtk3::Image'->new_from_icon_name("tools\-report\-bug",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Discover");
    $app->signal_connect('activate', sub {system "plasma\-discover &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("plasmadiscover",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Dolphin");
    $app->signal_connect('activate', sub {system "dolphin &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.kde\.dolphin",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Htop");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Show\ System\ Processes");
    $app->set_image('Gtk3::Image'->new_from_icon_name("htop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Info\ Center");
    $app->signal_connect('activate', sub {system "kinfocenter &"});
    $app->set_property('tooltip_text', "Centralized\ and\ convenient\ overview\ of\ system\ information");
    $app->set_image('Gtk3::Image'->new_from_icon_name("hwinfo",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ISO\ Image\ Writer");
    $app->signal_connect('activate', sub {system "isoimagewriter &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.kde\.isoimagewriter",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Journald\ Browser");
    $app->signal_connect('activate', sub {system "kjournaldbrowser &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("utilities\-log\-viewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KDE\ Partition\ Manager");
    $app->signal_connect('activate', sub {system "partitionmanager &"});
    $app->set_property('tooltip_text', "Manage\ disks\,\ partitions\,\ and\ file\ systems");
    $app->set_image('Gtk3::Image'->new_from_icon_name("partitionmanager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_kitty");
    $app->signal_connect('activate', sub {system "kitty &"});
    $app->set_property('tooltip_text', "Fast\,\ feature\-rich\,\ GPU\ based\ terminal");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kitty",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Konsole");
    $app->signal_connect('activate', sub {system "konsole &"});
    $app->set_property('tooltip_text', "Command\ line\ access");
    $app->set_image('Gtk3::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_KSystemLog");
    $app->signal_connect('activate', sub {system "ksystemlog\ \-qwindowtitle &"});
    $app->set_property('tooltip_text', "System\ log\ viewer\ tool");
    $app->set_image('Gtk3::Image'->new_from_icon_name("utilities\-log\-viewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Manage\ Printing");
    $app->signal_connect('activate', sub {system "xdg\-open\ http\:\/\/localhost\:631\/ &"});
    $app->set_property('tooltip_text', "CUPS\ Web\ Interface");
    $app->set_image('Gtk3::Image'->new_from_icon_name("cups",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Menu\ Editor");
    $app->signal_connect('activate', sub {system "kmenuedit &"});
    $app->set_property('tooltip_text', "Edit\ how\ applications\ are\ presented\ in\ app\ launchers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kmenuedit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Print\ Settings");
    $app->signal_connect('activate', sub {system "system\-config\-printer &"});
    $app->set_property('tooltip_text', "Configure\ printers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("printer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_System\ Monitor");
    $app->signal_connect('activate', sub {system "plasma\-systemmonitor &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Virtual\ Machine\ Manager");
    $app->signal_connect('activate', sub {system "virt\-manager &"});
    $app->set_property('tooltip_text', "Manage\ virtual\ machines");
    $app->set_image('Gtk3::Image'->new_from_icon_name("virt\-manager",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Menutray");
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Config");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/config\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Menu");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Schema");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/schema\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    $menu->append('Gtk3::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk3::ImageMenuItem'->new("_Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk3::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/chads\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk3'->main_quit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk3::ImageMenuItem'->new("_Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk3::Image'->new_from_icon_name("application\-exit",q{menu}));
    $quit->signal_connect('activate', sub { 'Gtk3'->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk3'->main;
